cruft update

diff --git a/.github/workflows/deploy-docs.yaml b/.github/workflows/deploy-docs.yaml
--- a/.github/workflows/deploy-docs.yaml
+++ b/.github/workflows/deploy-docs.yaml
@@ -1,31 +1,40 @@
+---
 name: Auto-deployment of cmdr Documentation
 on:
   push:
-    branches: [ main ]
+    branches: [main]
 
 jobs:
   build-docs:
     runs-on: ubuntu-latest
+
+    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
+    permissions:
+      contents: write  # to let mkdocs write the new docs
+      pages: write     # to deploy to Pages
+      id-token: write  # to verify the deployment originates from an appropriate source
+
     steps:
-    - name: Checkout
-      uses: actions/checkout@main
-      with:
-        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
-    
-    - name: Set up Python 3.
-      uses: actions/setup-python@v3
-      with:
-        python-version: 3.9
+      - name: Checkout
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0  # otherwise, you will failed to push refs to dest repo
 
-    - name: Install Poetry.
-      uses: snok/install-poetry@v1.3
+      - name: Set up Python.
+        uses: actions/setup-python@v4
+        with:
+          python-version: 3.9
 
-    - name: Install dependencies.
-      run: poetry install -E docs
-    
-    - name: Build documentation.
-      run: |
-        mkdir -p docs
-        touch docs/.nojekyll
-        poetry run gen-doc -d docs src/cmdr/schema/cmdr.yaml
-        poetry run mkdocs gh-deploy
+      - name: Install Poetry.
+        run: pipx install poetry
+
+      - name: Install dependencies.
+        run: poetry install -E docs
+
+      - name: Build documentation.
+        run: |
+          mkdir -p docs
+          touch docs/.nojekyll
+          make gendoc
+          ([ ! -f docs/about.md ] && cp src/docs/about.md docs/) || true
+          make mkd-gh-deploy
